cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cartapp'

urlpatterns = [
    path('detail/',views.cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/',views.cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name = 'cart_remove'),
]

myshop/urls.py
from os import stat
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'myshop'

urlpatterns = [
    path('',views.product_list, name = "product_list"),
    path('<slug:category_slug>/',views.product_list,name = 'product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name = 'product_detail'),
]
 
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myshoppingsite/urls.py
from collections import namedtuple

from django import urls
import payment
from payment.views import payment_canceled
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cartapp.urls', namespace = 'cart')),
    path('orders/',include('ordersapp.urls',namespace = 'orders')),
    path('payment/',include('payment.urls',namespace = 'payment')),
    path('',include('myshop.urls',namespace = 'myshop')),
]

myshopppingsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cartapp.urls', namespace = 'cart')),
    path('',include('myshop.urls',namespace = 'myshop')),
]

ordersapp/urls.py
from django.urls import path
from . import views

app_name = 'ordersapp'

urlpatterns = [
    path('create/',views.order_create,name = 'order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name = 'admin_order_detail'),
    path('admin/order/<int:id>/pdf/',views.admin_order_pdf, name = 'admin_order_pdf')
]

cartapp/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from myshop.models import Product

cartapp/forms.py
from typing import ForwardRef
from django import forms
from django.utils.translation import override

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form) :
    quantity = forms.TypedChoiceField(choices = PRODUCT_QUANTITY_CHOICES,coerce = int)
    override = forms.BooleanField(required = False,initial = False,widget = forms.HiddenInput)

cartapp/views.py
from django import forms
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_GET, require_POST
from myshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

from django.utils.translation import override

# Create your views here.

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id = product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product,quantity = cd['quantity'],override_quantity = cd['override'])
    
    
    return redirect('cartapp:cart_detail')

@require_POST
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id = product_id)
    cart.remove(product)
    return redirect('cartapp:cart_detail')
    
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial = {'quantity' : item['quantity'],'override' :True})
    return render(request,'cart/detail.html',{'cart':cart})

cartapp/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock  %}
{% block content %}
    <h1>Your Shopping Cart</h1>
    <table class = 'cart'>
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>            
            </tr>
        </thead>
        <tbody>
            {% for item in cart  %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href = "{{product.get_absolute_url}}"></a>
                                <img src="{% if product.image %}{{product.image.url}} {% else %}{% static "img/no_image.png" %}{% endif %}">
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method = "post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input type = "submit" value = "Update">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}"method="post">
                                <input type="submit" value="Remove">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">Rs.{{ item.price }}</td>
                        <td class="num">Rs.{{ item.total_price }}</td>

                    </tr>
                  
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">Rs.{{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right"> 
        <a href = "{% url "myshop:product_list" %}" class="buttonlight">Continue shopping</a>
        <a href = "{% url "orders:order_create" %}" class="button">Checkout</a>
    </p>

{% endblock %}